allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@ilic/compiler-wasm@0.10.0-snapshot.gc601f1c9d88e'
  - '@ilic/diagram@0.1.2-snapshot.gf27801bfebf0'
  - '@ilic/docx@0.1.2-snapshot.gf27801bfebf0'
  - '@ilic/language-service@0.1.2-snapshot.gf27801bfebf0'
  - '@ilic/monaco-adapter@0.1.2-snapshot.gf27801bfebf0'
  - '@ilic/repository-core@0.10.0-snapshot.gc601f1c9d88e'
  - '@ilic/tools@0.10.0-snapshot.gc601f1c9d88e'
onlyBuiltDependencies:
  - esbuild
